# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_id=ftblh
mod_version=20.1.4
maven_group=dev.ftb.mods
archives_base_name=ftb_little_helper
readable_name=FTB Little Helper
pack_format=15

# Minecraft properties
minecraft_version=1.20.1

# Dependencies
forge_version=47.3.3
parchment_minecraft_version=${mc_version}
parchment_mappings_version=2023.09.03
loader_version_range=[47.0,48.0)
kubejs_version=2001.6.5-build.14
architectury_version=9.2.14

curseforge_id=0000
